USE SparkToCode

CREATE TABLE DEPT (
    DUNM INT PRIMARY KEY,
    SSN INT,
    HIRDATE DATE,
    DN VARCHAR(100)
);

CREATE TABLE LOC (
    DUNM INT PRIMARY KEY,
    LOC VARCHAR(100) NOT NULL
);

CREATE TABLE EMP (
    SSN INT PRIMARY KEY,
    Fname VARCHAR(50) NOT NULL,
    Lname VARCHAR(50) NOT NULL,
    gender CHAR(1) CHECK (gender IN ('M', 'F')),
    super_id INT,
    BD DATE,
    DUNM INT,
    FOREIGN KEY (super_id) REFERENCES EMP(SSN),
    FOREIGN KEY (DUNM) REFERENCES DEPT(DUNM)
);

CREATE TABLE PROJECT (
    PNUM INT PRIMARY KEY,
    PN VARCHAR(100) NOT NULL,
    LOC VARCHAR(100),
    CITY VARCHAR(50),
    DUNM INT,
    FOREIGN KEY (DUNM) REFERENCES DEPT(DUNM)
);

CREATE TABLE WORK (
    SSN INT,
    PNUM INT,
    hours DECIMAL(5,2),
    PRIMARY KEY (SSN, PNUM),
    FOREIGN KEY (SSN) REFERENCES EMP(SSN),
    FOREIGN KEY (PNUM) REFERENCES PROJECT(PNUM)
);

CREATE TABLE dependent (
    dnum INT,
    BD DATE,
    GENDER CHAR(1) CHECK (GENDER IN ('M', 'F')),
    ssn INT,
    PRIMARY KEY (dnum, ssn),
    FOREIGN KEY (ssn) REFERENCES EMP(SSN)
);

ALTER TABLE DEPT 
ADD FOREIGN KEY (SSN) REFERENCES EMP(SSN);

ALTER TABLE LOC 
ADD FOREIGN KEY (DUNM) REFERENCES DEPT(DUNM);